### ISSUE TITLE
Can't reproduce README example 😞

### ISSUE THREAD

**Issue by LucyMcGowan** [jhudsl/matahari#1]
I am sure this is something weird on my end, but when I run the code in the README, my output is different (in fact I can't seem to populate the `value` column with anything except sessionInfo for the first and last column, and the rest of the columns with the exception of `expr` are all `NA`). I am using RStudio, running this inside a project.

```
dance_start()

4 + 4
#> [1] 8
"wow!"
#> [1] "wow!"
mean(1:10)
#> [1] 5.5

# Pause logging
dance_stop()
dance_tbl()
#> # A tibble: 6 x 6
#>   expr       value             path      contents  selection dt                 
#>   <list>     <list>            <list>    <list>    <list>    <dttm>             
#> 1 <language> <S3: sessionInfo> <lgl [1]> <lgl [1]> <lgl [1]> 2018-06-15 13:55:55
#> 2 <language> <lgl [1]>         <lgl [1]> <lgl [1]> <lgl [1]> 2018-06-15 13:55:55
#> 3 <language> <lgl [1]>         <lgl [1]> <lgl [1]> <lgl [1]> 2018-06-15 13:55:55
#> 4 <chr [1]>  <lgl [1]>         <lgl [1]> <lgl [1]> <lgl [1]> 2018-06-15 13:55:55
#> 5 <language> <lgl [1]>         <lgl [1]> <lgl [1]> <lgl [1]> 2018-06-15 13:55:55
#> 6 <language> <S3: sessionInfo> <lgl [1]> <lgl [1]> <lgl [1]> 2018-06-15 13:55:55
```

👆 Notice here all of my value column are `<lgl[1]>` (which are actually `NA`) compared to the readme where they differ based on what the value output would have been.

**Context**: I am trying to use this for a project with Jeff so trying to figure out the 📦 🎉

**Comment by seankross** [comment]
Hey @LucyMcGowan,

I now realize that the example in the readme was extremely user-unfriendly! I just updated it a little. Also make sure that you use `dance_start(value = TRUE)` so that you don't get `NA`s in the `value` column. Let me know if that clears things up!

Sean

**Comment by LucyMcGowan** [comment]
Ah yes 🎉! Got it, thank you @seankross!
