### ISSUE TITLE
Make clipboard optional for dance_report()

### ISSUE THREAD

**Issue by LucyMcGowan** [jhudsl/matahari#2]
I am trying to use `dance_report()` in RStudio Cloud, but it doesn't play nicely with the clipboard 😢. Would you be okay with this change? If so, I can submit a PR.

```
copy_base64 <- function(clip = TRUE) {
  enc_string <- base64_enc(serialize(dance_tbl(), NULL))
  if (clip) {
   write_clip(enc_string)
  } else {
   enc_string
 }
} 
```

**Comment by seankross** [comment]
Yeah looks good!
