### ISSUE TITLE
Don't save .dance in the global environment

### ISSUE THREAD

**Issue by hadley** [jhudsl/matahari#5]
Instead create a new environment inside your package:

```R
env <- new.env(parent = emptyenv())
```

And then use that env instead of `globalenv()`:

```R
dance_remove <- function() {
  if (!exists("dance", envir = env)
    return(invisible(FALSE)
      
  rm("dance", envir = env)
  invisible(TRUE)
}
```

**Comment by jtleek** [comment]
Good suggestion! @LucyMcGowan @seankross either of you have time to implement this or @hadley  if you get a sec could you send a PR?

**Comment by LucyMcGowan** [comment]
Thank you @hadley! I can do it 👍
