### ISSUE TITLE
dplyr dependency?

### ISSUE THREAD

**Issue by LucyMcGowan** [jhudsl/matahari#9]
@seankross, would it make you sad if I refactor this a bit to remove the dplyr dependency? I know dplyr isn't as heavy as it once was, but I've found that people get persnickety about picking up new packages that depend on it 🤷‍♀ BUT if you would rather it stays, I am fine with that too.

**Comment by seankross** [comment]
I can barely get out of bed in the morning without dplyr, but feel free to refactor!
